name: blender_4_0
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.2
  - pip=22.2.2
  - pyzmq=24.0.1
  - pip:
    - name: blender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.2
  - pip=22.2.2
  - pyzmq=24.0.1
  - pip:
    - https://github.com/SuperFCR/rpg_esim/releases/download/v1.0/bpy-4.0.0-cp310-cp310-manylinux_2_28_x86_64.whl


